version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: node:16.13.0-alpine
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=db_user
      - PG_PASSWORD=secret
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}